export const LIST_SUCCESS = 'LIST_SUCCESS';
export const REGISTER_SUCCESS = 'REGISTER_SUCCESS';
export const LOGIN_SUCCESS = 'LOGIN_SUCCESS';
export const OSLIST_SUCCESS = 'OSLIST_SUCCESS';
export const FAVLIST_SUCCESS = 'FAVLIST_SUCCESS';
export const FORGOTPASSWORD_SUCCESS= 'FORGOTPASSWORD_SUCCESS';
export const RECOVERYUSERNAME_SUCCESS= 'RECOVERYUSERNAME_SUCCESS';
export const RESETPASSWORD_SUCCESS ="RESETPASSWORD_SUCCESS";
export const CREATENEWDESK_SUCCESS = "CREATENEWDESK_SUCCESS";
export const CARTOONCOLORPICK_SUCCESS="CARTOONCOLORPICK_SUCCESS";
export const FAVPICKLIST_SUCCESS ="FAVPICKLIST_SUCCESS";
export const COLLECTION_SUCCESS ="COLLECTION_SUCCESS";
export const DECK_SUCCESS = "DECK_SUCCESS";
export const ACCOUNTSETTINGS_SUCCESS ="ACCOUNTSETTINGS_SUCCESS";
export const DELETEDECK_SUCCESS = "DELETEDECK_SUCCESS"; 
export const EDITDECK_SUCCESS = "EDITDECK_SUCCESS";
export const SINGLDECK_SUCCESS = "SINGLDECK_SUCCESS";
export const SEARCHFILTER_SUCCESS ="SEARCHFILTER_SUCCESS";
export const PIN_SUCCESS =  "PIN_SUCCESS";
export const DISCOVERYLIST_SUCCESS = "DISCOVERYLIST_SUCCESS";
export const DASHBOARD_GETLIST_SUCCESS = "DASHBOARD_GETLIST_SUCCESS";
export const GET_USER_EMAIL_SUCCESS = "GET_USER_EMAIL_SUCCESS";
export const EDIT_DECK_DETAILS_SUCCESS  = "EDIT_DECK_DETAILS_SUCCESS";
export const EDIT_DECK_DUBLICATE_SUCCESS ="EDIT_DECK_DUBLICATE_SUCCESS";


// export const FOOTER_SUCCESS =FOOTER_SUCCESS;


